python -u run.py \
    --task_name pretrain \
    --root_path ./datasets/ETT-small/ \
    --data_path ETTh1.csv \
    --model_id ETTh1 \
    --model HtulTS \
    --data ETTh1 \
    --features M \
    --input_len 336 \
    --enc_in 7 \
    --d_model 128 \
    --depth 4 \
    --patch_len 16 \
    --stride 8 \
    --learning_rate 0.0001 \
    --weight_decay 0.01 \
    --batch_size 16 \
    --use_noise 0 \
    --train_epochs 50 \
    --lr_decay 0.95 \
    --gpu 0 \
    --tfc_weight 0.05 \
    --tfc_warmup_steps 500 \
    --projection_dim 128 \
    --use_real_imag 1 \
    --use_disentanglement 0