python -u run.py \
    --task_name finetune \
    --downstream_task classification \
    --root_path datasets/Epilepsy/ \
    --model_id Epilepsy \
    --model HtulTS \
    --data Epilepsy \
    --input_len 206 \
    --enc_in 3 \
    --num_classes 4 \
    --d_model 128 \
    --patch_len 16 \
    --stride 8 \
    --dropout 0.1 \
    --batch_size 16 \
    --gpu 0 \
    --lr_decay 1.0 \
    --lradj decay \
    --patience 100 \
    --learning_rate 0.001 \
    --train_epochs 100 \
    --use_norm 0 \
    --use_forgetting 0 \
    --use_real_imag 1 \
    --projection_dim 128
