for pred_len in 12 24 36 48; do
    python -u run.py \
        --task_name finetune \
        --is_training 1 \
        --root_path ./datasets/PEMS/ \
        --data_path PEMS03.npz \
        --model_id PEMS03 \
        --model HtulTS \
        --data PEMS03 \
        --features M \
        --input_len 12 \
        --seq_len 12 \
        --label_len 12 \
        --pred_len $pred_len \
        --e_layers 2 \
        --enc_in 358 \
        --dec_in 358 \
        --c_out 358 \
        --n_heads 8 \
        --d_model 128 \
        --d_ff 512 \
        --patch_len 16 \
        --stride 8 \
        --dropout 0.2 \
        --head_dropout 0.1 \
        --batch_size 8 \
        --gpu 0 \
        --lr_decay 0.5 \
        --lradj step \
        --time_steps 1000 \
        --scheduler cosine \
        --patience 3 \
        --learning_rate 0.0005 \
        --pct_start 0.3 \
        --train_epochs 10 \
        --use_noise 0 \
        --use_forgetting 1 \
        --forgetting_type activation \
        --forgetting_rate 0.1 \
        --projection_dim 128 \
        --use_real_imag 1 \
        --load_checkpoints "" \
        --num_workers 0
done
